### PR TITLE
Allow extending DefaultImportSource to provide customization to indexing definitions

### PR DESCRIPTION
**Pull request by serpentblade**
Allow DefaultImportSource to be extendable
- Allow overriding default chunk size

Move Index creation from static method on Index to a method of ImportSource.
 - Allow custom index rules to be applied to generating Indexes if DefaultImportSource is extended.

### CODE REVIEW

**Comment by matchish** [comment]
What is the reason to extend `DefaultImportSource`?
You can bind your own `ImportSourceFactory` and  use your own `ImportSource` https://github.com/matchish/laravel-scout-elasticsearch#eager-load

**Comment by matchish** [comment]
I believe `ImportSource` don't need to know about elasticsearch. So its not his responsibility

**Comment by matchish** [comment]
Why did you move index creation to `ImportSource`? I don't see any changes there

**Comment by serpentblade** [comment]
All of these changes were implemented to support defining an `Index` via a different means for model and adjusting how they are indexed.

`DefaultImportSource` already provides an effective implementation strategy for imports, and by allowing it to be extended a consumer of this library can leverage the `ImportSourceFactory` binding to provide a derivation of `DefaultImportSource` without having to entirely implement the `ImportSource` interface.

There were two primary requirements I had in my system that lead to these changes.  One was being able to have a variable chunk size defined per model, the later was being able to define the index settings and mappings via a programmatic means that did not rely on putting them all into config files.

The first requirement was straight forward, I created `getChunkSize()` to allow the chunk size to be provided by the ImportSource definition. I have some models that I can batch import in chunks of 5000 very quickly and efficiently, while some more complex models with deep nested relationships I need to import in chunks of 100 to reduce the memory footprint and query complexities in eager loading.  

The latter requirement forced the refactoring of the code definitions that ended up moving   `Index::fromSource()` to `ImportSource->defineIndex()`.  Having `Index::fromSource` as a static method meant I had no control in my implementation over how an index could be defined; I was always locked into having to defining mappings via configs and the index name would always be just a timestamp thrown onto the end of the defined index name.  By moving that code into `ImportSource`, the existing implementation remains identical, but it grants a consumer the ability to define the index definition via the ImportSource interface.

Being able to leverage an extendable `DefaultImportSource` I was able to create a subclass and only override `getChunkSize()` and `defineIndex()` to meet my needs.  With it being `final` previously, I'd have to either copy the entire `DefaultImportSource` code or create an ImportSource definition that forwarded calls to DefaultImportSource for all the other methods I didn't want to implement. But the project is open source, so what's the point in forcing a class to be final?

**Comment by matchish** [comment]
You have good reason but we need to find another implementation.
`final` is sign that class isn't part of public api and backward compatibility can't be guaranteed. 
From `ImportSourceFactory` you can return your own different `ImportSource`s with different chunk size.
Creating index inside `ImportSource` violate **S**OLID principle. So we need to find another way

**Comment by serpentblade** [comment]
What's the concern about backwards compatibility?  If I've implemented my own `ImportSource` and the usage of that interface contract changes it would break just as well.  Give me an example of where backwards compatibility would be an issue by not making it final where any other forced implementation of `ImportSource` wouldn't have the same situation.

I don't know if I agree with the strict requirement of the SOLID principle you're placing on the `defineIndex()` method.  For example, `ImportSource` already defines `searchableAs()` as a means to get the import source's index name.  In fact, that method is critical to the implementation of building an `Index` from `ImportSource`.  `ImportSource` already has responsibility in defining the name of the index , providing the models to be indexed, along with customized scopes to assure the shape of the data is accurate.  Would it also not be an extension of that latter part to suppose that it can define the schema/settings for the index as well?  If the primary concern is that it references `Index`, that can be remedied by moving the method back into `Index::fromImportSource` and adding new interface methods to provide the index settings and mappings which can be overridden by a custom implementation.

**Comment by matchish** [comment]
I make all classes by default final with private methods by default. It's my preferred style. I can change access type later but I need reason for it. The advantage of this approach is I more free when refactor. I don't care about backward compatibility because I don't change public api and I wouldn't break someone project. 
I agree about `searchableAs` that it also violate SOLID, for me it's mean we have to remove this method from `ImportSource`
If we have `defineIndex` in `ImportSource` we have  one to one relation index with source and for somebody it can be not true. So I prefer to evolve the package to separate `Index` and `ImportSource`
We need customisable mappings between index and import source

**Pull request closed without merging**
