### PR TITLE
Add support for php 8

### PR DESCRIPTION
**Pull request by fkeloks**
In this PR, nothing more than an update of the package to make it compatible with php 8.  
**The version of Laravel does not change**

Changes :

-  "php": "^8.0",
-  "roave/better-reflection": "^5.0"

### CODE REVIEW

**Comment by matchish** [comment]
Hello. Have you tried this branch? https://github.com/wuerthcs/maet-server/pull/198

**Comment by matchish** [comment]
Version 5 support php8

**Comment by fkeloks** [comment]
Hello,

I saw this branch too late. By the way, in the [Releases tab of Github](https://github.com/matchish/laravel-scout-elasticsearch/releases), the "latest" version is v4.0.9 and not this v5.

I still proposed this MR because it doesn't imply any update of other packages, no switch to [laravel/scout v9](https://github.com/matchish/laravel-scout-elasticsearch/commit/e37b978c088a4fd47c8295c8e377d24a03d4570a#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R23) for example.

However I'm not sure about the usefulness of my PR, feel free to remove it if you want.

Have a nice day! 😃

**Comment by matchish** [comment]
I agree that it make sense to consider to merge it but for now your PR don't pass scrutinizer. So should be fixed first

**Pull request closed without merging**
