### PR TITLE
Add possibility to use instances of classes that implement ONGR\ElasticsearchDSL\BuilderInterface as values for where() in Laravel Scout query builder

### PR DESCRIPTION
**Pull request by swayok**
For https://github.com/matchish/laravel-scout-elasticsearch/issues/259

### CODE REVIEW

**Comment by hkulekci** [comment]
Thanks @swayok. This is nice to solve this problem, and I appreciate your effort. Could we write a test to see when the problem happened and what we solved exactly in this PR?

**Comment by swayok** [comment]
@hkulekci added test case for RangeQuery but I wasn't able to run it.

**Comment by hkulekci** [comment]
@matchish could you approve to be able to see test results?

**Comment by hkulekci** [comment]
> @hkulekci added test case for RangeQuery but I wasn't able to run it.

Hey @swayok thanks for the quick response and the tests. Let's wait for @matchish. I hope he will approve soon.

**Comment by hkulekci** [comment]
LGTM. I prefer splitting the tests into different functions. But at least for now, it shows that the implementation is working.  If you can, move the test into a new test function as below :

```php
    public function test_search_with_custom_filter()
    {
        $dispatcher = Product::getEventDispatcher();
        Product::unsetEventDispatcher();

        $kindleCheapAmount = rand(1, 5);
        $iphoneLuxuryAmount = rand(1, 5);
        $iphonePromoUsedAmount = rand(1, 5);
        $iphonePromoNewAmount = rand(6, 10);
        $iphonePromoLikeNewAmount = rand(1, 5);
        $iphonePromoUsedAndLikeNewAmount = $iphonePromoLikeNewAmount + $iphonePromoUsedAmount;

        factory(Product::class, $kindleCheapAmount)->states(['iphone', 'cheap'])->create();
        factory(Product::class, $iphoneLuxuryAmount)->states(['iphone', 'luxury'])->create();
        factory(Product::class, $iphonePromoUsedAmount)->states(['iphone', 'promo', 'used'])->create();
        factory(Product::class, $iphonePromoNewAmount)->states(['iphone', 'promo', 'new'])->create();
        factory(Product::class, $iphonePromoLikeNewAmount)->states(['iphone', 'promo', 'like new'])->create();

        Product::setEventDispatcher($dispatcher);

        Artisan::call('scout:import');

        // Promo Product Test
        $iphonePromoUsedAndLikeNewWithRange = Product::search('iphone')
            ->where('price', new RangeQuery('price', [
                RangeQuery::GTE => 100,  // Promo Products
                RangeQuery::LTE => 100,  // Promo Products
            ]))
            ->whereIn('type', ['used', 'like new'])
            ->get();

        $this->assertEquals($iphonePromoUsedAndLikeNewWithRange->count(), $iphonePromoUsedAndLikeNewAmount);
        $this->assertInstanceOf(Product::class, $iphonePromoUsedAndLikeNewWithRange->first(), 'Promo Product Assert');

        // Luxury Product Test
        $iphoneLuxuryUsedAndLikeNewWithRange = Product::search('iphone')
            ->where('price', new RangeQuery('price', [
                RangeQuery::GTE => 1000, // Luxury Products
            ]))
            ->get();

        $this->assertEquals($iphoneLuxuryUsedAndLikeNewWithRange->count(), $iphoneLuxuryAmount, 'Luxury Product Count Assert');
        $this->assertInstanceOf(Product::class, $iphoneLuxuryUsedAndLikeNewWithRange->first());

        // Cheap Product Test
        $iphoneCheapWithRange = Product::search('iphone')
            ->where('price', new RangeQuery('price', [
                RangeQuery::LTE => 70, // Cheap Products
            ]))
            ->get();

        $this->assertEquals($kindleCheapAmount, $iphoneCheapWithRange->count(), 'Cheap Product Count Assert');
        $this->assertInstanceOf(Product::class, $iphoneCheapWithRange->first());
    }
```

Thanks. ^_^

**Comment by matchish** [comment]
And could you update README plz

**Comment by swayok** [comment]
Done

**Comment by hkulekci** [comment]
Hey, @swayok, thanks for the quick update. I appreciate it. 

@matchish LGTM!

**Comment by matchish** [comment]
Released! Thanks @swayok. Really nice feature

**Pull request merged**
