### PR TITLE
Merge config from vendor

### PR DESCRIPTION
**Pull request by ametad**
Closes https://github.com/matchish/laravel-scout-elasticsearch/issues/84

### CODE REVIEW

**Comment by ametad** [comment]
Hi @matchish , 

A 'good first issue' the label said, I thought I help you a little bit :)

**Comment by matchish** [comment]
Thanks for the help. Could you add a test for your code?

**Comment by matchish** [comment]
You can add the test here https://github.com/matchish/laravel-scout-elasticsearch/blob/master/tests/Feature/ScoutElasticSearchServiceProviderTest.php

**Comment by ametad** [comment]
Could you point me in a direction on how I could do the tests myself?

Because I see "orchestra/testbench" I thought I could run the tests on this package in an isolated way, as described here:

https://medium.com/@realgoodsystem/laravel-package-testing-with-testbench-component-orchestral-testbench-7d7ec95d9be8

But I cannot get it to work yet... help is very welcome :)

**Comment by ametad** [comment]
I get these errors now:

> PDOException: SQLSTATE[HY000] [1045] Access denied for user 'forge'@'localhost' (using password: NO)

Do the tests only work as part of an fully configured Laravel installation? Or can I also test the package on it's own (isolated)?

**Comment by ametad** [comment]
Wait... I have it working! A local config `phpunit.xml` with the correct env variables did the trick.

I tried the standard as described here https://github.com/orchestral/testbench#memory-sqlite-connection, but that didn't work:

```xml
<phpunit>

    // ...

    <php>
        <env name="DB_CONNECTION" value="testing"/>
    </php>

</phpunit>
```
Do you perhaps know why that doesn't work out of the box?

**Comment by matchish** [comment]
Hello! Thanks for help) 

To run tests locally just run `make test`

**Comment by matchish** [comment]
I've fixed ci. You can rebase your branch then you can be sure that `make test` is working

**Comment by ametad** [comment]
Crap... I think I messed up a little with rebasing, now commits are double(?). And because I used my master branch for this MR I cannot force push a reset of the branch. 

I come back to this later, but maybe I have to begin from scratch (a clean fork).

**Comment by matchish** [comment]
You can cherry-pick commits what you need into a new branch and create new PR

**Comment by ametad** [comment]
In favor of #98

**Pull request closed without merging**
