### PR TITLE
Support for Laravel 8

### PR DESCRIPTION
**Pull request by SachinAgarwal1337**

### CODE REVIEW

**Comment by matchish** [comment]
Could you take care of errors?

**Comment by SachinAgarwal1337** [comment]
@matchish looked like legacy factory was required since model factories are in older way. 
what's weird is, I am able to do the composer install/update locally and it is working just fine. 
I am not able to figure out why it is failing on travis. 

Can you help me understand this?

**Comment by matchish** [comment]
https://travis-ci.com/github/matchish/laravel-scout-elasticsearch/jobs/397670845#L479
Seems like `larastan` don't support higher order functions and we have to tell larastan to ignore it 
https://github.com/nunomaduro/larastan/issues/200
https://github.com/nunomaduro/larastan/blob/master/docs/errors-to-ignore.md

**Comment by matchish** [comment]
TODO: 
FIx styleci errors
Update changelog
Bump version

**Comment by nmokkenstorm** [comment]
> Seems like `larastan` don't support higher order functions and we have to tell larastan to ignore it

A bit out of left field maybe, but I'm working on fixing this, both as a standalone package & generally within Larastan. Installing [this](https://github.com/Sustainabil-IT/phpstan-higher-order-collections) might just fix your issue, and if it doesn't I'd love to have feedback on what breaks.

**Pull request merged**
