### PR TITLE
Fix #135 Compatible with Laravel Telescope in Composer require-dev

### LINKED ISSUE #135: [BUG] Compatible with Laravel Telescope in Composer require-dev
**Describe the bug**
`php artisan scout:import` crashes when Laravel Telescope is configured as "dev" requirement, to only load in "local" environment.

**To Reproduce**
1. Require Laravel Telescope as dev req.: `composer require laravel/telescope --dev`
1. Install Telescope as described here https://laravel.com/docs/telescope#installation, for dev!
    1. `php artisan telescope:install` and `php artisan migrate`.
    1. After running telescope:install, you should remove the TelescopeServiceProvider service provider registration from your app configuration file. Instead, manually register the service provider in the register method of your AppServiceProvider.
1. Try `php artisan scout:import` (without extra argument). This throws exception: "Class 'Laravel\Telescope\TelescopeApplicationServiceProvider' not found"

**Expected behavior**
Running `scout:import` should only try to load classes with `require_once $file;` that are Eloquent model and Searchable only. If possible.

**Additional context**

I think the problem is located here:
https://github.com/matchish/laravel-scout-elasticsearch/blob/06c90914668942b23ffaff7d58af5b9db1901fb1/src/Searchable/SearchableListFactory.php#L69

There ALL php files in the `app` directory are loaded, even when it is not used at runtime.

In my setup the class `\App\Providers\TelescopeServiceProvider` should only be loaded in dev, but is now loaded anyway by `\Matchish\ScoutElasticSearch\Searchable\SearchableListFactory::getProjectClasses`. 

The intention of my setup is made clear in `\App\Providers\AppServiceProvider::register`:

```php
        if ($this->app->isLocal()) {
            $this->app->register(TelescopeServiceProvider::class);
        }
```

**Version**
Versions of Laravel, Scout, and the package.
Laravel 5.8
Scout: 7.2.1
Package: 3.0.3

### PR DESCRIPTION
**Pull request by ametad**
Feedback is welcome :-)

### CODE REVIEW

**Comment by ametad** [comment]
#135

**Comment by matchish** [comment]
Great contribution) Thanks!
Why did you renamed tests/laravel/app/library/CustomHitsIteratorAggregate.php to tests/laravel/app/Library/CustomHitsIteratorAggregate.php ?

**Comment by matchish** [comment]
Also pls `git apply` https://github.styleci.io/analyses/vQNn3r
Bump the package version  to `4.0.3` and update `CHANGELOG.md`

**Comment by ametad** [comment]
> Great contribution) Thanks!

You're welcome!

> Why did you renamed tests/laravel/app/library/CustomHitsIteratorAggregate.php to tests/laravel/app/Library/CustomHitsIteratorAggregate.php ?

Because of PSR-4. "Library" should reflect the namespace, which starts with a capital letter.

**Comment by ametad** [comment]
> Also pls `git apply` https://github.styleci.io/analyses/vQNn3r

We'll do, until it turns green.

> Bump the package version to `4.0.3` and update `CHANGELOG.md`

Oke.

**Comment by ametad** [comment]
I also would like the resulting commits to be cherry picked into the 3.x branch. If this is a small thing for you, would you help me with that?

**Comment by ametad** [comment]
It is done and in the green!

Please consider my question:
> I also would like the resulting commits to be cherry picked into the 3.x branch. If this is a small thing for you, would you help me with that?

**Comment by matchish** [comment]
Sure I'll copy the feature to 3.x. Thanks again for your great contribution!

**Pull request merged**
