### PR TITLE
Fix for using pagination with custom query in Scout Builder.

### PR DESCRIPTION
**Pull request by Malezha**
### Problem
When calling the paginate method on `Laravel\Scout\Builder`, the `getTotalCount` method is triggered.
```php
    public function paginate($perPage = null, $pageName = 'page', $page = null)
    {
        // method implementation

        return Container::getInstance()->makeWith(LengthAwarePaginator::class, [
            'items' => $results,
            'total' => $this->getTotalCount($results), // Calculates the total count of results
            'perPage' => $perPage,
            'currentPage' => $page,
            'options' => [
                'path' => Paginator::resolveCurrentPath(),
                'pageName' => $pageName,
            ],
        ])->appends('query', $this->query);
    }
```
The `getTotalCount` method retrieves the total count of results from the search engine. It includes a check for a query callback, which may trigger an additional database query if specified.
```php
    protected function getTotalCount($results)
    {
        $engine = $this->engine();

        $totalCount = $engine->getTotalCount($results);

        // Checks if a query callback is defined, which could result in an additional database query.
        if (is_null($this->queryCallback)) {
            return $totalCount;
        }

        $ids = $engine->mapIdsFrom($results, $this->model->getScoutKeyName())->all();

        if (count($ids) < $totalCount) {
            $ids = $engine->keys(tap(clone $this, function ($builder) use ($totalCount) {
                // Problem: Setting `Builder::$limit` here does not affect the actual query.
                // Attempts to set a limit for the query based on the total count or the existing limit.
                $builder->take(
                    is_null($this->limit) ? $totalCount : min($this->limit, $totalCount)
                );
            }))->all();
        }

        return $this->model->queryScoutModelsByIds(
            $this, $ids
        )->toBase()->getCountForPagination();
    }
```
Additionally, the default `take` method on `Laravel\Scout\Builder` does not allow setting a response size limit in this implementation.

### Proposed Fix

In the `SearchFactory::create` method, add a check for the presence of the `$builder->limit` parameter before examining the `$options` parameter. This adjustment preserves compatibility with the pagination implementation by ensuring that any explicitly set limit in $builder is prioritized.

This change will allow the pagination functionality to respect a custom limit if defined, while maintaining backward compatibility with existing configurations.

### CODE REVIEW

**Comment by Malezha** [comment]
@matchish also I can implement #252 in this request for make it compatible in future.

**Comment by matchish** [comment]
Great work on this pull request! The addition to set the size based on the builder's limit is a valuable enhancement.

However, I've noticed that `setSize` is now being called in two places which might override each other:

When `$builder->limit` is set
When the `size` option is passed
This could lead to unintended behavior. We might want to consider:

Restricting the usage of both to avoid conflicts
Warning the client about this potential issue
Additionally, to avoid introducing breaking changes, it might be better to move the new changes below the size option handling.

What do you think?

**Comment by matchish** [comment]
Thanks for suggesting that, @Malezha! 👍 It'd be great if you could implement #252 . Feel free to implement it as part of this request

> @matchish also I can implement #252 in this request for make it compatible in future.

**Comment by Malezha** [comment]
@matchish this update maintains backward compatibility, as it only applies limit handling for pagination, following the same approach as Eloquent's paginator, which ignores limit and offset when paginating.

**Comment by matchish** [comment]
Yes, it follows the same approach as Eloquent's paginator, but I'm not sure about backward compatibility. For example, if someone is using `-take(10)->options(['size' => 20])`, before the update, it would return 10 results, but after the update, it might return 20.

I understand that no reason to write code this way, but someone could forget to remove after experiments. I just prefer to not bump to new major version if it is not necessary.

Would it cause any issues if we keep the `size` in `options` as the dominant setting? Or should we disregard this risk as minor and proceed with Eloquent's paginator approach without a major version bump?

**Comment by Malezha** [comment]
We will have to abandon support for the `size` parameter in the `options()` method, because then we will have two sources that are not synchronized with each other.
Unfortunately, `$options` is public and anyone can use the direct assignment of the size value.
I think should leave only `$builder->limit` as the main response size setting, which is overridden when using pagination, because exactly this option is used in Scout.
As for the option with `options(['size' => 10])`, it should not affect the code at all, just as it does not affect it now.

**Comment by Malezha** [comment]
I made suggested changes and added some behavioral tests.
If the proposed is good in your opinion, then I would add a description in documentation of how it works.

**Comment by Malezha** [comment]
@matchish which version I should use?

**Comment by matchish** [comment]
Not sure what is happening but looks like not only we have failed upload to codecov https://github.com/codecov/codecov-action/issues/1580#issuecomment-2472328494

**Comment by matchish** [comment]
I'm thinking about `7.9.0` as new feature introduced but not breaking changes
> @matchish which version I should use?

**Comment by Malezha** [comment]
I updated version in the changelog.
Try run the workflow again, maybe it was already fixed by coverage service.

**Comment by Malezha** [comment]
Branch merged

**Comment by matchish** [comment]
Released! Thank you for your valuable contribution! Great Job!

**Pull request merged**
