### PR TITLE
[^] Fixed SQL statements getting slower and slower when importing big…

### PR DESCRIPTION
**Pull request by deviljoker5200**
Fixed SQL statements getting slower and slower when importing big data。

### Screenshot of importing big data before fixing it

微信截图_20210201125338
微信截图_20210201125358
It's almost 20 seconds a SQL statement to the end.Five million data takes more than an hour

### Screenshot of importing big data after fixing it
微信截图_20210201134442
微信截图_20210201134453

A single SQL is 8ms on average.The import completed in a few minutes

In general, rely on the forPageAfterId method.

But the way to save the last ID doesn't feel good enough. You must have a better way to solve it.Here's one way to think about it.

### CODE REVIEW

**Comment by matchish** [comment]
Yeah I've tried to fix it here https://github.com/matchish/laravel-scout-elasticsearch/issues/25 and https://github.com/matchish/laravel-scout-elasticsearch/issues/78
but postponed as I remember because of only latest mysql have required functionality. Probably we need multiple implementations of import job

**Comment by matchish** [comment]
Also your pr don't pass test

**Comment by deviljoker5200** [comment]
> Also your pr don't pass test

Sorry, I didn't write the test script, if I modify it and it passes, will the code merge?

**Comment by matchish** [comment]
I can merge it as an alternative implementation of import job. To do it we need to inject your implementation through ioc container

**Comment by shahriar-b** [comment]
any update on this?

**Comment by matchish** [comment]
Still no fixed PR

**Comment by matchish** [comment]
@deviljoker5200 I have improved import performance but don't have big enough dataset to test. Could you try this branch https://github.com/matchish/laravel-scout-elasticsearch/tree/parallel-import ?

**Pull request closed without merging**
