### PR TITLE
lazyMap Implementation in ElasticSearchEngine

### PR DESCRIPTION
**Pull request by derpierre65**
Hello everyone,

we have implemented the lazyMap method, would be nice if this could come in php8 branch.

Please review.

### CODE REVIEW

**Comment by matchish** [comment]
I'm not sure it works with mixed search https://github.com/matchish/laravel-scout-elasticsearch/tree/php8#search-amongst-multiple-models

**Comment by matchish** [comment]
I could merge it but it prone to debugging for users when they use mixed search. Take a look to https://github.com/matchish/laravel-scout-elasticsearch/blob/master/src/ElasticSearch/EloquentHitsIteratorAggregate.php and https://github.com/matchish/laravel-scout-elasticsearch/blob/704d03e4c8ea442494f0ebc8b5cedadda2982633/src/Engines/ElasticSearchEngine.php#L107

**Comment by matchish** [comment]
I would be greate if you could cover your code with integration tests. See example https://github.com/matchish/laravel-scout-elasticsearch/blob/master/tests/Integration/Elasticsearch/HitsIteratorAggregateTest.php

**Comment by ghostzero** [comment]
@derpierre65 please have a look into this.

**Comment by Broutard** [comment]
We use this Elastic driver with Laravel Nova... lazyMap is required for Nova global search.
The proposed implementation works in my case.

**Comment by Broutard** [comment]
Nova "global search" run a query per model so I don't know if it works for that use case.

**Comment by matchish** [comment]
@Broutard Any idea how to prevent debugging MultiSearch debugging that don't use Nova? Is there a way to understand environment where the package works?

**Comment by matchish** [comment]
Or at least we need to throw meaningful error when a user call `cursor` method on MixedSearch.

**Pull request closed without merging**
